In [1]:
pip install flask-ngrok

In [2]:
pip install youtube_dl

     |████████████████████████████████| 1.9 MB 7.7 MB/s 


In [3]:
pip install -U flask-cors

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
from flask import Flask
from flask_ngrok import run_with_ngrok
from keras.models import load_model
import cv2
import numpy as np
from flask_cors import CORS
from flask import jsonify
from __future__ import unicode_literals
import youtube_dl
import time
from flask import request
app = Flask(__name__)
run_with_ngrok(app)  


model = load_model('/content/drive/MyDrive/content/cctvkaggle_final.h5')

#video_path = '/content/drive/MyDrive/content/fight2.mp4'
video_path = ''


@app.route("/")
def home():
    return "Welcome to flask backend !"


def download_the_video(video_url):
  print("Video DOWNLOADING STARTED")
  ydl_opts = {'outtmpl': 'videoToTest.mp4'}

  with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    ydl.download(['https://www.youtube.com/watch?v=ULkzOl70pIQ'])

  return 'videoToTest.mp4'
                   
@app.route("/videoURL")  
def predict_by_model():
    # before that link the code with the extension
    #download the video url and use that video
    
    videourl = request.args.get('video')
    print(str(videourl))
    video_title = download_the_video(str(videourl))


    video_path = video_title
    time.sleep(4)
    print("Video DOWNLOADED")
    try:
      category =['NonViolence', 'Violence']
      frames = []
      frame_count = 0
      queue=[]

      capture = cv2.VideoCapture(video_path)
      count = 0
      while (capture.isOpened() and count < 4):
          print(count)
          ret, frame = capture.read()
            # Bail out when the video file ends
          frame = cv2.resize(frame, (90, 90))
          if not ret:
              break

      # Save each frame of the video to a list
          frame_count += 1
          frames.append(frame)

          if frame_count < 4:
              continue # capture frames until you get the required number for sequence
          else:
              frame_count = 0

      # For each frame, extract feature and prepare it for classification
          sequence = []
          for image in frames:
              sequence.append(image) 

          prediction = model.predict(np.expand_dims(sequence, axis=0))
          print(prediction)
          queue.append(prediction)
          count += 1


      results = np.array(queue).mean(axis=0)
      i = category[np.argmax(results)]
     
      print('Predicted: '+ i)
      capture.release()
      return jsonify(statusOfVideo = str(i))
    except Exception as e:
      return jsonify(statusOfVideo = str(i))
     
CORS(app)
app.run()

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)


 * Running on http://e9b7057cf35e.ngrok.io
 * Traffic stats available on http://127.0.0.1:4040
https://www.youtube.com/watch?v=Bkd2-QcBl_o
Video DOWNLOADING STARTED
[youtube] ULkzOl70pIQ: Downloading webpage
[youtube] ULkzOl70pIQ: Downloading player 02486e7d
[download] Destination: videoToTest.f136.mp4
[download] 100% of 19.87MiB in 00:01
[download] Destination: videoToTest.mp4.f140
[download] 100% of 3.45MiB in 00:00
[ffmpeg] Merging formats into "videoToTest.mp4"
Deleting original file videoToTest.f136.mp4 (pass -k to keep)
Deleting original file videoToTest.mp4.f140 (pass -k to keep)
Video DOWNLOADED
0
0
0
0
[[0.40085953 0.59914047]]
1
1
1
1
[[0.3551537  0.64484626]]
2
2
2
2


127.0.0.1 - - [29/Jul/2021 01:37:58] "GET /videoURL?video=https://www.youtube.com/watch?v=Bkd2-QcBl_o HTTP/1.1" 200 -


[[0.26682392 0.7331761 ]]
3
3
3
3
[[0.32835022 0.6716498 ]]
Predicted: Violence
https://www.youtube.com/watch?v=_5jlfu8N1E0
Video DOWNLOADING STARTED
[youtube] ULkzOl70pIQ: Downloading webpage
[download] videoToTest.mp4 has already been downloaded and merged
Video DOWNLOADED
0
0
0
0
[[0.40085953 0.59914047]]
1
1
1
1
[[0.3551537  0.64484626]]
2
2
2
2


127.0.0.1 - - [29/Jul/2021 01:38:59] "GET /videoURL?video=https://www.youtube.com/watch?v=_5jlfu8N1E0 HTTP/1.1" 200 -


[[0.26682392 0.7331761 ]]
3
3
3
3
[[0.32835022 0.6716498 ]]
Predicted: Violence
https://www.youtube.com/watch?v=_5jlfu8N1E0
Video DOWNLOADING STARTED
[youtube] ULkzOl70pIQ: Downloading webpage
[download] videoToTest.mp4 has already been downloaded and merged
Video DOWNLOADED
0
0
0
0
[[0.40085953 0.59914047]]
1
1
1
1
[[0.3551537  0.64484626]]
2
2
2
2


127.0.0.1 - - [29/Jul/2021 01:39:20] "GET /videoURL?video=https://www.youtube.com/watch?v=_5jlfu8N1E0 HTTP/1.1" 200 -


[[0.26682392 0.7331761 ]]
3
3
3
3
[[0.32835022 0.6716498 ]]
Predicted: Violence
https://www.youtube.com/watch?v=_5jlfu8N1E0
Video DOWNLOADING STARTED
[youtube] ULkzOl70pIQ: Downloading webpage
[download] videoToTest.mp4 has already been downloaded and merged
Video DOWNLOADED
0
0
0
0
[[0.40085953 0.59914047]]
1
1
1
1
[[0.3551537  0.64484626]]
2
2
2
2


127.0.0.1 - - [29/Jul/2021 01:40:54] "GET /videoURL?video=https://www.youtube.com/watch?v=_5jlfu8N1E0 HTTP/1.1" 200 -


[[0.26682392 0.7331761 ]]
3
3
3
3
[[0.32835022 0.6716498 ]]
Predicted: Violence
https://www.youtube.com/watch?v=_5jlfu8N1E0
Video DOWNLOADING STARTED
[youtube] ULkzOl70pIQ: Downloading webpage
[download] videoToTest.mp4 has already been downloaded and merged
Video DOWNLOADED
0
0
0
0
[[0.40085953 0.59914047]]
1
1
1
1
[[0.3551537  0.64484626]]
2
2
2
2


127.0.0.1 - - [29/Jul/2021 01:41:09] "GET /videoURL?video=https://www.youtube.com/watch?v=_5jlfu8N1E0 HTTP/1.1" 200 -


[[0.26682392 0.7331761 ]]
3
3
3
3
[[0.32835022 0.6716498 ]]
Predicted: Violence
https://www.youtube.com/watch?v=_5jlfu8N1E0
Video DOWNLOADING STARTED
[youtube] ULkzOl70pIQ: Downloading webpage
[download] videoToTest.mp4 has already been downloaded and merged
Video DOWNLOADED
0
0
0
0
[[0.40085953 0.59914047]]
1
1
1
1
[[0.3551537  0.64484626]]
2
2
2
2


127.0.0.1 - - [29/Jul/2021 01:41:35] "GET /videoURL?video=https://www.youtube.com/watch?v=_5jlfu8N1E0 HTTP/1.1" 200 -


[[0.26682392 0.7331761 ]]
3
3
3
3
[[0.32835022 0.6716498 ]]
Predicted: Violence
https://www.youtube.com/watch?v=_5jlfu8N1E0
Video DOWNLOADING STARTED
[youtube] ULkzOl70pIQ: Downloading webpage
[download] videoToTest.mp4 has already been downloaded and merged
Video DOWNLOADED
0
0
0
0
[[0.40085953 0.59914047]]
1
1
1
1
[[0.3551537  0.64484626]]
2
2
2
2


127.0.0.1 - - [29/Jul/2021 01:42:57] "GET /videoURL?video=https://www.youtube.com/watch?v=_5jlfu8N1E0 HTTP/1.1" 200 -


[[0.26682392 0.7331761 ]]
3
3
3
3
[[0.32835022 0.6716498 ]]
Predicted: Violence
https://www.youtube.com/watch?v=_5jlfu8N1E0
Video DOWNLOADING STARTED
[youtube] ULkzOl70pIQ: Downloading webpage
[download] videoToTest.mp4 has already been downloaded and merged
Video DOWNLOADED
0
0
0
0
[[0.40085953 0.59914047]]
1
1
1
1
[[0.3551537  0.64484626]]
2
2
2
2


127.0.0.1 - - [29/Jul/2021 01:44:50] "GET /videoURL?video=https://www.youtube.com/watch?v=_5jlfu8N1E0 HTTP/1.1" 200 -


[[0.26682392 0.7331761 ]]
3
3
3
3
[[0.32835022 0.6716498 ]]
Predicted: Violence
https://www.youtube.com/watch?v=_5jlfu8N1E0
Video DOWNLOADING STARTED
[youtube] ULkzOl70pIQ: Downloading webpage
[download] videoToTest.mp4 has already been downloaded and merged
Video DOWNLOADED
0
0
0
0
[[0.40085953 0.59914047]]
1
1
1
1
[[0.3551537  0.64484626]]
2
2
2
2


127.0.0.1 - - [29/Jul/2021 01:47:09] "GET /videoURL?video=https://www.youtube.com/watch?v=_5jlfu8N1E0 HTTP/1.1" 200 -


[[0.26682392 0.7331761 ]]
3
3
3
3
[[0.32835022 0.6716498 ]]
Predicted: Violence
https://www.youtube.com/watch?v=_5jlfu8N1E0
Video DOWNLOADING STARTED
[youtube] ULkzOl70pIQ: Downloading webpage
[download] videoToTest.mp4 has already been downloaded and merged
Video DOWNLOADED
0
0
0
0
[[0.40085953 0.59914047]]
1
1
1
1
[[0.3551537  0.64484626]]
2
2
2
2


127.0.0.1 - - [29/Jul/2021 01:47:38] "GET /videoURL?video=https://www.youtube.com/watch?v=_5jlfu8N1E0 HTTP/1.1" 200 -


[[0.26682392 0.7331761 ]]
3
3
3
3
[[0.32835022 0.6716498 ]]
Predicted: Violence
https://www.youtube.com/watch?v=_5jlfu8N1E0
Video DOWNLOADING STARTED
[youtube] ULkzOl70pIQ: Downloading webpage
[download] videoToTest.mp4 has already been downloaded and merged
Video DOWNLOADED
0
0
0
0
[[0.40085953 0.59914047]]
1
1
1
1
[[0.3551537  0.64484626]]
2
2
2
2


127.0.0.1 - - [29/Jul/2021 01:47:43] "GET /videoURL?video=https://www.youtube.com/watch?v=_5jlfu8N1E0 HTTP/1.1" 200 -


[[0.26682392 0.7331761 ]]
3
3
3
3
[[0.32835022 0.6716498 ]]
Predicted: Violence
https://www.youtube.com/watch?v=_5jlfu8N1E0
Video DOWNLOADING STARTED
[youtube] ULkzOl70pIQ: Downloading webpage
[download] videoToTest.mp4 has already been downloaded and merged
Video DOWNLOADED
0
0
0
0
[[0.40085953 0.59914047]]
1
1
1
1
[[0.3551537  0.64484626]]
2
2
2
2


127.0.0.1 - - [29/Jul/2021 01:49:37] "GET /videoURL?video=https://www.youtube.com/watch?v=_5jlfu8N1E0 HTTP/1.1" 200 -


[[0.26682392 0.7331761 ]]
3
3
3
3
[[0.32835022 0.6716498 ]]
Predicted: Violence
https://www.youtube.com/
Video DOWNLOADING STARTED
[youtube] ULkzOl70pIQ: Downloading webpage
[download] videoToTest.mp4 has already been downloaded and merged
Video DOWNLOADED
0
0
0
0
[[0.40085953 0.59914047]]
1
1
1
1
[[0.3551537  0.64484626]]
2
2
2
2


127.0.0.1 - - [29/Jul/2021 01:50:31] "GET /videoURL?video=https://www.youtube.com/ HTTP/1.1" 200 -


[[0.26682392 0.7331761 ]]
3
3
3
3
[[0.32835022 0.6716498 ]]
Predicted: Violence
https://www.youtube.com/watch?v=_5jlfu8N1E0
Video DOWNLOADING STARTED
[youtube] ULkzOl70pIQ: Downloading webpage
[download] videoToTest.mp4 has already been downloaded and merged
Video DOWNLOADED
0
0
0
0
[[0.40085953 0.59914047]]
1
1
1
1
[[0.3551537  0.64484626]]
2
2
2
2


127.0.0.1 - - [29/Jul/2021 01:50:56] "GET /videoURL?video=https://www.youtube.com/watch?v=_5jlfu8N1E0 HTTP/1.1" 200 -


[[0.26682392 0.7331761 ]]
3
3
3
3
[[0.32835022 0.6716498 ]]
Predicted: Violence
https://www.youtube.com/watch?v=_5jlfu8N1E0
Video DOWNLOADING STARTED
[youtube] ULkzOl70pIQ: Downloading webpage
[download] videoToTest.mp4 has already been downloaded and merged
Video DOWNLOADED
0
0
0
0
[[0.40085953 0.59914047]]
1
1
1
1
[[0.3551537  0.64484626]]
2
2
2
2


127.0.0.1 - - [29/Jul/2021 01:51:12] "GET /videoURL?video=https://www.youtube.com/watch?v=_5jlfu8N1E0 HTTP/1.1" 200 -


[[0.26682392 0.7331761 ]]
3
3
3
3
[[0.32835022 0.6716498 ]]
Predicted: Violence
https://www.youtube.com/watch?v=_5jlfu8N1E0
Video DOWNLOADING STARTED
[youtube] ULkzOl70pIQ: Downloading webpage
[download] videoToTest.mp4 has already been downloaded and merged
Video DOWNLOADED
0
0
0
0
[[0.40085953 0.59914047]]
1
1
1
1
[[0.3551537  0.64484626]]
2
2
2
2


127.0.0.1 - - [29/Jul/2021 01:51:59] "GET /videoURL?video=https://www.youtube.com/watch?v=_5jlfu8N1E0 HTTP/1.1" 200 -


[[0.26682392 0.7331761 ]]
3
3
3
3
[[0.32835022 0.6716498 ]]
Predicted: Violence
https://www.youtube.com/watch?v=_5jlfu8N1E0
Video DOWNLOADING STARTED
[youtube] ULkzOl70pIQ: Downloading webpage
[download] videoToTest.mp4 has already been downloaded and merged
Video DOWNLOADED
0
0
0
0
[[0.40085953 0.59914047]]
1
1
1
1
[[0.3551537  0.64484626]]
2
2
2
2


127.0.0.1 - - [29/Jul/2021 01:53:35] "GET /videoURL?video=https://www.youtube.com/watch?v=_5jlfu8N1E0 HTTP/1.1" 200 -


[[0.26682392 0.7331761 ]]
3
3
3
3
[[0.32835022 0.6716498 ]]
Predicted: Violence
https://www.youtube.com/watch?v=_5jlfu8N1E0
Video DOWNLOADING STARTED
[youtube] ULkzOl70pIQ: Downloading webpage
[download] videoToTest.mp4 has already been downloaded and merged
Video DOWNLOADED
0
0
0
0
[[0.40085953 0.59914047]]
1
1
1
1
[[0.3551537  0.64484626]]
2
2
2
2


127.0.0.1 - - [29/Jul/2021 01:53:56] "GET /videoURL?video=https://www.youtube.com/watch?v=_5jlfu8N1E0 HTTP/1.1" 200 -


[[0.26682392 0.7331761 ]]
3
3
3
3
[[0.32835022 0.6716498 ]]
Predicted: Violence
https://www.youtube.com/watch?v=_5jlfu8N1E0
Video DOWNLOADING STARTED
[youtube] ULkzOl70pIQ: Downloading webpage
[download] videoToTest.mp4 has already been downloaded and merged
Video DOWNLOADED
0
0
0
0
[[0.40085953 0.59914047]]
1
1
1
1
[[0.3551537  0.64484626]]
2
2
2
2


127.0.0.1 - - [29/Jul/2021 01:55:38] "GET /videoURL?video=https://www.youtube.com/watch?v=_5jlfu8N1E0 HTTP/1.1" 200 -


[[0.26682392 0.7331761 ]]
3
3
3
3
[[0.32835022 0.6716498 ]]
Predicted: Violence


In [ ]:
# Testing the video downloader code

from __future__ import unicode_literals
import youtube_dl

ydl_opts = {'outtmpl': 'videoToTest.mp4'}

with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    ydl.download(['https://www.youtube.com/watch?v=ULkzOl70pIQ'])

[youtube] ULkzOl70pIQ: Downloading webpage
[download] Destination: videoToTest.f136.mp4
[download] 100% of 19.87MiB in 00:01
[download] Destination: videoToTest.mp4.f140
[download] 100% of 3.45MiB in 00:00
[ffmpeg] Merging formats into "videoToTest.mp4"
Deleting original file videoToTest.f136.mp4 (pass -k to keep)
Deleting original file videoToTest.mp4.f140 (pass -k to keep)
